version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: clean-css-cli
    versions:
    - 4.3.0
    - 5.0.0
    - 5.0.1
    - 5.1.0
    - 5.2.0
    - 5.2.1
    - 5.2.2
